# Generated by Django 2.2.5 on 2021-08-20 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('survey_app', '0011_auto_20210820_0659'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.BigIntegerField(default=1629442790000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=250, null=True, unique=True)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('product_category', models.PositiveIntegerField(choices=[(7, 'Grains, Nuts, and Beans'), (8, 'Leafy Vegetables'), (9, 'Meat, Fish, and Poultry Products'), (10, 'Root Crops, Mushrooms'), (11, 'Fruits'), (12, 'Sugar & Sweeteners')], null=True)),
                ('like', models.PositiveIntegerField(default=0)),
                ('created_at', models.BigIntegerField(default=1629442790000)),
                ('updated_at', models.BigIntegerField(default=1629442790000)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='survey_app.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'preference',
                'verbose_name_plural': 'preferences',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price_ht', models.FloatField(blank=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers_site.Cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey_app.Product')),
            ],
        ),
    ]
