# Generated by Django 2.2.5 on 2021-08-20 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_site', '0002_auto_20210820_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.BigIntegerField(default=1629438416000),
        ),
        migrations.AlterField(
            model_name='preference',
            name='created_at',
            field=models.BigIntegerField(default=1629438416000),
        ),
        migrations.AlterField(
            model_name='preference',
            name='updated_at',
            field=models.BigIntegerField(default=1629438416000),
        ),
    ]
