# Generated by Django 2.2.5 on 2021-08-31 00:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers_site', '0004_auto_20210825_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.BigIntegerField(default=1630371052000),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AlterField(
            model_name='preference',
            name='created_at',
            field=models.BigIntegerField(default=1630371052000),
        ),
        migrations.AlterField(
            model_name='preference',
            name='product_category',
            field=models.PositiveIntegerField(choices=[(1, 'Grains, Nuts, Root Crops'), (2, 'Leafy Vegetables'), (3, 'Poultry and Meat')], null=True),
        ),
        migrations.AlterField(
            model_name='preference',
            name='updated_at',
            field=models.BigIntegerField(default=1630371052000),
        ),
    ]
