# Generated by Django 2.2.5 on 2021-08-31 00:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers_site', '0005_auto_20210831_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.BigIntegerField(default=1630371239000),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='preference',
            name='created_at',
            field=models.BigIntegerField(default=1630371239000),
        ),
        migrations.AlterField(
            model_name='preference',
            name='updated_at',
            field=models.BigIntegerField(default=1630371239000),
        ),
    ]
