# Generated by Django 2.2.5 on 2021-08-31 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_app', '0019_auto_20210831_0103'),
        ('customers_site', '0006_auto_20210831_0054'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartItem',
            new_name='Item',
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.BigIntegerField(default=1630371826000),
        ),
        migrations.AlterField(
            model_name='preference',
            name='created_at',
            field=models.BigIntegerField(default=1630371826000),
        ),
        migrations.AlterField(
            model_name='preference',
            name='updated_at',
            field=models.BigIntegerField(default=1630371826000),
        ),
    ]
