# Generated by Django 2.2.5 on 2021-06-23 06:40

from django.db import migrations
import survey_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_app', '0007_auto_20210622_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=survey_app.models.CustomDateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=survey_app.models.CustomDateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='created_at',
            field=survey_app.models.CustomDateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=survey_app.models.CustomDateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=survey_app.models.CustomDateTimeField(auto_now=True),
        ),
    ]
