# Generated by Django 2.2.5 on 2021-06-28 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_app', '0008_auto_20210623_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.IntegerField(default=1624847725),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.IntegerField(default=1624847725),
        ),
    ]
