# Generated by Django 2.2.5 on 2021-06-28 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_app', '0009_auto_20210628_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.IntegerField(default=1624847998),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.IntegerField(default=1624847998),
        ),
        migrations.AlterField(
            model_name='log',
            name='created_at',
            field=models.IntegerField(default=1624847998),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.IntegerField(default=1624847998),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.IntegerField(default=1624847998),
        ),
    ]
